version: "3"

services:
  db_postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres
    env_file:
      - .env

  celery:
    build: .
    command: celery -A investsphere_api worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db_postgres
      - redis
    env_file:
      - .env

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  celery_beat:
    build: .
    command: celery -A investsphere_api beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx_dev/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app

volumes:
  postgres_data:
  static: