version: "3"

services:
  db_postgres:
    image: postgres:14
    env_file:
      - backend_investsphere/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
      - certs:/etc/nginx/certs
      - ./config/certbot/www:/var/www/certbot
    depends_on:
      - django_app

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; certbot certonly --webroot --webroot-path=/var/www/certbot -d api.investsphere.cl --non-interactive --agree-tos -m tuemail@example.com && while :; do certbot renew; sleep 12h & wait $${!}; done;'

volumes:
  postgres_data:
  static:
  certs: