version: "3"

services:
  db_postgres:
    image: postgres:14
    env_file:
      - backend_investsphere/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
      - certbot_certs:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      - django_app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      - nginx

volumes:
  postgres_data:
  static:
  certbot_certs:
  certbot_challenges:
