version: "3"

services:
  celery:
    build: .
    command: celery -A investsphere_api worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379