# Generated by Django 4.2 on 2024-09-05 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0002_company_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('historical_variation', models.DecimalField(decimal_places=2, help_text='Historical variation percentage', max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_of_shares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_investments', to='app_users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_date', models.DateField()),
                ('historical_variation', models.DecimalField(decimal_places=2, help_text='Percentage of variation', max_digits=5)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund_manager', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_founds', to='app_users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_founds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixedTermDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiration_date', models.DateField()),
                ('estimated_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate as a percentage', max_digits=5)),
                ('bank', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_term_deposits', to='app_users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_term_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptocurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_date', models.DateTimeField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_currency', models.CharField(max_length=10)),
                ('currency_bought', models.CharField(max_length=10)),
                ('amount_of_bought_currency', models.DecimalField(decimal_places=8, max_digits=15)),
                ('platform', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criptocurrency_transactions', to='app_users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criptocurrency_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
